"""Add info_pages table for More menu content

Revision ID: 44e5744b2306
Revises: 197a26deadc8
Create Date: 2026-09-03 09:44:10.956257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44e5744b2306'
down_revision: Union[str, Sequence[str], None] = '197a26deadc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('cta_label', sa.String(length=50), nullable=True),
    sa.Column('cta_target', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_info_pages_id'), 'info_pages', ['id'], unique=False)
    op.create_index(op.f('ix_info_pages_slug'), 'info_pages', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_info_pages_slug'), table_name='info_pages')
    op.drop_index(op.f('ix_info_pages_id'), table_name='info_pages')
    op.drop_table('info_pages')
    # ### end Alembic commands ###
